spring:
  servlet:
    multipart:
      max-file-size: 5MB
  datasource:
    url: ${ICRITIC_DB_URL:jdbc:postgresql://localhost:5432/icritic}
    username: ${ICRITIC_DB_USERNAME:root}
    password: ${ICRITIC_DB_PASSWORD:root}
  jpa:
    database: POSTGRESQL
  kafka:
    bootstrap-servers: ${ICRITIC_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    email-notification-topic: ${ICRITIC_KAFKA_EMAIL_NOTIFICATION_TOPIC:email-notification}
    password-reset-request-topic: ${ICRITIC_KAFKA_PASSWORD_RESET_REQUEST_TOPIC:password-reset-request}
    password-reset-topic: ${ICRITIC_KAFKA_PASSWORD_RESET_TOPIC:password-reset}
    password-change-topic: ${ICRITIC_KAFKA_PASSWORD_CHANGE_TOPIC:password-change}
    email-reset-request-topic: ${ICRITIC_KAFKA_EMAIL_RESET_REQUEST_TOPIC:email-reset-request}
    email-reset-topic: ${ICRITIC_KAFKA_EMAIL_RESET_TOPIC:email-reset}
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:fvn04we78bftt69}
  error:
    include-stacktrace: never
  application:
    properties:
      jwtSecret: ${ICRITIC_JWT_SECRET:b7c995a4acd856ea084449fa0000bd086d38888ecddd4d8f4b6b6805f03b028270bfcb5bc7de7c9f24fe7e8a317e633fedb2a3a4441f5af4dc7933e0ff6d7d1b}
      jwtRefreshSecret: ${ICRITIC_JWT_REFRESH_SECRET:659402b168ac90cba8ea6f5954d268879415d099a0848912d023f5afc038c82cbaae463a23d69958c922eebed281a69d83231262f926f9442e8306fd4e6b7e3f'}
      jwtExpiration: ${ICRITIC_JWT_EXPIRATION:600}
      jwtRefreshExpiration: ${ICRITIC_JWT_REFRESH_EXPIRATION:604800}
      azure:
        connectionString: ${ICRITIC_AZURE_CONNECTION_STRING}
        containerName: ${ICRITIC_AZURE_CONTAINER_NAME}
        containerHostUrl: ${ICRITIC_AZURE_CONTAINER_URL:https://icriticstagestorage.blob.core.windows.net/icritic-pictures}
server:
  port: 8081
  error:
    include-stacktrace: never
