apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: icritic-stage-keyvault-provider
spec:
  provider: azure
  secretObjects:
    - data:
        - key: ICRITIC_DB_URL
          objectName: ICRITIC-DB-URL
        - key: ICRITIC_DB_USERNAME
          objectName: ICRITIC-DB-USERNAME
        - key: ICRITIC_DB_PASSWORD
          objectName: ICRITIC-DB-PASSWORD
        - key: ICRITIC_JWT_SECRET
          objectName: ICRITIC-JWT-SECRET
        - key: ICRITIC_JWT_REFRESH_SECRET
          objectName: ICRITIC-JWT-REFRESH-SECRET
        - key: ICRITIC_AZURE_CONNECTION_STRING
          objectName: ICRITIC-AZURE-CONNECTION-STRING
        - key: ICRITIC_AZURE_CONTAINER_NAME
          objectName: ICRITIC-AZURE-CONTAINER-NAME
      secretName: icritic-users-secrets
      type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "59bc0c69-c7f6-4f1b-989f-5be0232b8cb5"
    keyvaultName: "icritic-stage-keyvault"
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: ICRITIC-DB-URL
          objectType: secret             
          objectVersion: ""
        - |
        - |
          objectName: ICRITIC-DB-USERNAME
          objectType: secret             
          objectVersion: ""
        - |
        - |
          objectName: ICRITIC-DB-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: ICRITIC-JWT-SECRET
          objectType: secret
          objectVersion: ""
        - |
          objectName: ICRITIC-JWT-REFRESH-SECRET
          objectType: secret             
          objectVersion: ""
        - |
          objectName: ICRITIC-AZURE-CONNECTION-STRING
          objectType: secret
          objectVersion: ""
      - |
          objectName: ICRITIC-AZURE-CONTAINER-NAME
          objectType: secret
          objectVersion: ""
    tenantId: ebc53480-3f79-45b4-8df1-c0824e236476