create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
create table countries (id  bigserial not null, name varchar(255), primary key (id));
create table users (id  bigserial not null, active boolean, created_at timestamp, description varchar(255), email varchar(255) not null, email_reset_date timestamp, email_reset_hash varchar(255), name varchar(255) not null, new_email_reset varchar(255), password varchar(255) not null, password_reset_date timestamp, password_reset_hash varchar(255), role varchar(255), updated_at timestamp, country_id int8, primary key (id));
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint FKjlpks00ofkq3sqd9hqiavv5lg foreign key (country_id) references countries;
